version: '3.9'
services:
  soap:
    container_name: wbd_jax_ws
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - .:/app
    build: .
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql:latest
    container_name: wbd_soap
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=soap
      - MYSQL_DATABASE=wbd_soap
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db: