CREATE TABLE IF NOT EXISTS logging (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    description CHAR(255) NOT NULL,
    ip CHAR(16) NOT NULL,
    endpoint CHAR(255) NOT NULL,
    requested_at TIMESTAMP NOT NULL DEFAULT NOW()
);